# Generated by Django 5.2 on 2025-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
    ]
