# Generated by Django 5.2 on 2025-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Загружен'), ('UNDER_REVIEW', 'На проверке'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен'), ('DELETED', 'Удалён')], default='UPLOADED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Загружен'), ('UNDER_REVIEW', 'На проверке'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен'), ('DELETED', 'Удалён')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
