# Generated by Django 5.2 on 2025-05-14 20:45

import request_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0002_alter_document_status_alter_documenthistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to=request_app.models.candidate_document_path),
        ),
    ]
