# Generated by Django 5.2 on 2025-05-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0002_remove_candidate_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
