# Generated by Django 5.2 on 2025-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0003_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
