# Generated by Django 5.2 on 2025-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('PRE_DIPLOMA', 'Преддипломная'), ('PRODUCTION', 'Производственная'), ('EDUCATIONAL', 'Учебная')], max_length=20, null=True, verbose_name='Тип практики'),
        ),
        migrations.AddField(
            model_name='interview',
            name='resume_type',
            field=models.CharField(choices=[('JOB', 'Работа'), ('PRACTICE', 'Практика')], default='JOB', max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='resume',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('PRE_DIPLOMA', 'Преддипломная'), ('PRODUCTION', 'Производственная'), ('EDUCATIONAL', 'Учебная')], max_length=20, null=True, verbose_name='Тип практики'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_type',
            field=models.CharField(choices=[('JOB', 'Работа'), ('PRACTICE', 'Практика')], default='JOB', max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Паспорт', 'Паспорт'), ('Приписное/Военник', 'Приписное/Военник'), ('Аттестат/Диплом', 'Аттестат/Диплом'), ('Справка с психодиспансера', 'Справка с психодиспансера'), ('Справка с наркодиспансера', 'Справка с наркодиспансера'), ('Справка о несудимости', 'Справка о несудимости'), ('Согласие на обработку персональных данных', 'Согласие на обработку персональных данных'), ('ИНН', 'ИНН'), ('СНИЛС', 'СНИЛС'), ('Трудовая книжка (опционально)', 'Трудовая книжка (опционально)'), ('Договор о практике', 'Договор о практике'), ('Заявление на практику', 'Заявление на практику')], max_length=100, verbose_name='Тип документа'),
        ),
    ]
