# Generated by Django 5.2 on 2025-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0004_remove_candidate_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
