# Generated by Django 5.2 on 2025-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0005_alter_resume_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Комментарий'),
        ),
    ]
