# Generated by Django 5.2 on 2025-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0005_interview_practice_type_interview_resume_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_to_email',
            field=models.BooleanField(default=False, verbose_name='Отправлено на email'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REGISTRATION', 'Регистрация'), ('RESUME_STATUS', 'Статус резюме'), ('INTERVIEW', 'Собеседование'), ('DOCUMENT', 'Документ'), ('HIRE', 'Прием'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип'),
        ),
    ]
