# Generated by Django 5.2 on 2025-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0006_resume_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'Собеседование', 'verbose_name_plural': 'Собеседования'},
        ),
        migrations.AddField(
            model_name='interview',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
