# Generated by Django 5.2 on 2025-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0006_notification_sent_to_email_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_type',
            field=models.CharField(blank=True, choices=[('PROGRAMMER', 'Инженер-программист'), ('METHODOLOGIST', 'Методолог'), ('SPECIALIST', 'Специалист')], max_length=20, null=True, verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_type',
            field=models.CharField(blank=True, choices=[('PROGRAMMER', 'Инженер-программист'), ('METHODOLOGIST', 'Методолог'), ('SPECIALIST', 'Специалист')], max_length=20, null=True, verbose_name='Тип работы'),
        ),
    ]
