# Generated by Django 5.2 on 2025-05-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0007_interview_job_type_resume_job_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
