# Generated by Django 5.2 on 2025-05-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0008_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='date_of_birth',
        ),
    ]
