# Generated by Django 5.2 on 2025-05-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0009_remove_candidate_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='practice_type',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='resume_type',
        ),
    ]
