# Generated by Django 5.2 on 2025-05-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0010_remove_interview_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='request_app.resume'),
        ),
    ]
