# Generated by Django 5.2 on 2025-05-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0011_interview_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='has_successful_interview',
        ),
    ]
